steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: /bin/sh
  args:
    - '-c'
    - |
       docker build -t eu.gcr.io/${PROJECT_ID}/${_IMAGE_NAME} \
         --build-arg ML_MODELS_BUCKET=${_ML_MODELS_BUCKET} \
         .
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/${PROJECT_ID}/${_IMAGE_NAME}']

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: /bin/sh
  args:
    - '-c'
    - |
       sed -e "s/\$$ANALYTICS_PROJECT/$_ANALYTICS_PROJECT/g" workflow.yaml.tmpl > workflow.yaml
  dir: /workspace/conf

- name: 'eu.gcr.io/${PROJECT_ID}/kubeflow-tools'
  entrypoint: /bin/sh
  args:
    - '-c'
    - |
       bin/kfp.sh ${_KUBEFLOW_HOST} ${REPO_NAME} /workspace/conf/workflow.yaml

substitutions:
  _IMAGE_NAME: train-iris
  _ML_MODELS_BUCKET: climate-analytics-ml-models
